global.MilesTicketEventMethods = MilesTicketEventMethods
global.recipeHandler = recipeHandler
global.tooltipHandler = tooltipHandler
global.inventoryChangedHandler = inventoryChangedHandler
global.itemRightClickedHandler = itemRightClickedHandler
global.serverLoadedHandler = serverLoadedHandler
global.entityInteractedHandler = entityInteractedHandler
global.loggedInHandler = loggedInHandler